---
title: Digital Education Footprint - Deep Learning and The Future of Education
author:
  - name: Fanli (Christian) Zheng
    affiliation: dyad x machina
    email: thechristianramsey@gmail.com
  - name: Haohan Wang
    affiliation: dyad x machina
    email: haohan723@gmail.com    
abstract: |
  We live in a time where people can freely access high quality video lectures, how-tos, journal articles, books with a click of a button. Our education can no longer be said to mostly comprised of what we learned in school. New technologies have pushed us to learn new things we may on the fly and such motivated individuals find themselves online watching lectures about programming, complex systems, neuroscience, deep learning or a how-to in order to write an article or to better understand the world they are living in. But yet, most of what we watch or read on the web, goes unnoticed and 
 
bibliography: sigproc.bib
output: rticles::acm_article
---


# Introduction 
Let's start with a future view of an individual's education. Many of us have used the internet to educate ourselves with the abundance of high quality videos, papers, articles, podcasts and how-tos all over the web. Let us imagine that all of what you have learned online (throughout the entirety of your life), from the hundreds of Youtube videos, Wikipedia articles, Nature papers, and podcasts you've read, watched, or listened to, were all consolidated into what we might call a **digital education footprint**. 

The **digital education footprint** would string together our online education into a concrete representation of one's online education and could be extended by more formal settings. By showcasing the broad range of individual's knowledge (making digital music) as well as the places they've went deeper than most (deep learning or philosophy of mathematics), we could begin to accept education as a life-long journey rather than a monolithic part of an individual's past. We could also begin to see a more accurate depiction of someone's education that could be updated each and everytime they educate themselves. With every new year, their footprint would evolve just as the very thread of their lives would. 

In this essay, I will propose a new way to approach education which will require significant effort to bring to life the benefits of a **digital education footprint** or similar, but the benefits will surely outweigh the costs. 
> A society where individuals do not simply compete for a degree but where they can feel safe to follow their noses and still be recognised for their trail
> A society where an individual's knowledge is derived not from what we know about a degree
> A society that better understands itself, through the understanding of the many journey's it's members have taken and the collective knowledge that has gone mostly unaccounted for

I will also show that this imagined future is not only **desirable** for society but also that much of it is currently feasible mainly due to the most recent advances in machine learning, and in particular deep learning, which will enable us to begin designing such a future today. 

## Concerns

 There are 3 popular concerns that I will attempt to address in this article about online learning in the present and the future. I will attempt to address them here and in the implementation section below.
 
- The first concern is that the learning is often passive
- The second concern is that the information remains untested and therefore doesn't truly make the leap from information to true knowledge.
- The third concern is that even if the two concerns above were met definitively, it would not be possible to .

### Passive Consumption

### Untested Knowledge 

### Predictability


## Concepts 

### Digital Education Footprint
The concept of a digital education footprint is is a custom symbol and profile that represents one's education relative to that of others. Each symbol should be somewhat unique and the profile could capture the general education as well as the intricacies. 
A symbol which represents somethng as complex as one's education will likely not be enough for employeers and co-workers to understand the . A symbol must show that one is in a particular "class" while also  Symbols generally have to make trade-offs

### Trails 
 between the complexity of what it represents and it's ability to convey , the legi from dealing with the task of reduction of info. So we introduce **Trails** or **Missions** which show how someone has traversed the uy
If most people had their digital education footprint, they would be 

### Human Knowledge Graph
We have so far introduced **digital education footprint** and **trails**, which claim to be the right elements to synthesis one's education. But how does one create a path? From video to video? From topic to topic? If so, how might a machine decide on the topic? We have had plenty of advances in topic models but perhaps what we actually need is a graph of human knowledge. This graph, like Google's knowledge graph, should be generated both from the current structure of education and also driven by unsupervised learning of new topics that don't exist on today's knowledge graph.

This graph would be useful so content on the web could be easily mapped to the graph adn relate one user to another as well as create trails.

## From Data to Wisdom (DIKW)


 
Over time, it is plausible, that our digital education footprint would be the most important representation of an individuals level of education. Even more important than our primary education; it has done much to make us predictable, but it has sacrificed the true range of an individual's gained knowledge and wisdom coming from any other place than the institution is willing to give credit for. 

Since we've largely rely upon large institutions to educate groups of individuals, many have grown deeply familiar with having a perfectly demarcated path towards a degree, so it has been much harder for individuals to use this abundance of knowledge to chart their own educational journey in today's fast moving world.

 being   us how to the peer pressure of cohorts, self-learning  learned Imagine that if you signed up for a job, your primary consideration and also your digital education could be conveyed as a path through the web that others attempt to follow or mix and match. Now let us imagine a world where our digital education fingerprint allowed us to



## Part I - Rethinking education
 
  E2QA - a theoretical neural network architecture to generate questions and answers from video.
  
  
## Part III - Supporting theories for deep learning

Theory of the learnable
Mutual Information
Joint probability


## Part IV - Survey of empirical results

RNN / CNN
VQA
Encoder/Decoder

## Part V - Call to action

## Part VI - Evaluation
OLD NLP - Grammar 
Deep NLP - Word2Vec

# Conclusion

# References

---
references:
- id: meier2012
  title: Professinal Android 4 Application Development
  author: 
  - family: Meier
    given: Reto
  type: book
  publisher: John Wiley & Sons, Inc.
  issued:
    year: 2012
    month: 5
- id: fenner2012a
  title: One-click science marketing
  author:
  - family: Fenner
    given: Martin
  container-title: Nature Materials
  volume: 11
  URL: 'https://doi.org/10.1038/nmat3283'
  DOI: 10.1038/nmat3283
  issue: 4
  publisher: Nature Publishing Group
  page: 261-263
  type: article-journal
  issued:
    year: 2012
    month: 3
...

